{
	'name':'CKWI Maintenance',
    'version': '14.0.0.1',
    'author': 'taufikid',
    'website': 'http://www.taufikid.com',
    'license': 'LGPL-3',
    'category': 'Maintenance',
    'description': 'equipment Maintenance, checklist ',
    'summary':'Maintenance Repair Operation',
	'depends': ['hr_maintenance','stock','maintenance','project','purchase_requisition','report_xlsx'],
	'data': [
		'security/ir.model.access.csv',
        'security/maintenance_security.xml',
        'view/maintenance_plan_view.xml',
        'view/maintenance_timetable_view.xml',
        'view/maintenance_daily_view.xml',
        'view/menu.xml',
		'data/maintenance_inprogress.xml',
        'data/workorder_sequence.xml',
		'data/maintenace_repaire_mail.xml',
        'data/maintenance_stage.xml',
        'view/maintenance_request_view.xml',
        'view/maintenance_stage.xml',
        'view/stock_location_view.xml',
        'view/job_order_view.xml',
        'view/res_config_view.xml',
        'view/maintenance_checklist.xml',
        'view/maintenance_equipment_view.xml',
        'view/purchase_requisition.xml',
        'report/report_action_view.xml',
    ],
    'images': [
        'static/description/icon.png',
    ],
    "external_dependencies": {"python": ["dateutil"]},
    "post_init_hook": "post_init_hook",
    "installable": True,
    'auto_install': False,

}